# Countries and their service mappings
countries:
  US:
    service: "atomic"
    environments:
      dev: true
      stage: false
      live: false
  DE:
    service: "upvest"
    environments:
      dev: false
      stage: false
      live: false
  FR:
    service: "upvest"
    environments:
      dev: true
      stage: false
      live: false
  UK:
    service: "upvest"
    environments:
      dev: true
      stage: false
      live: false