# Environment-specific overrides
environments:
  dev:
    services:
      atomic:
        base_url: "https://dev-api.atomic.com"
      upvest:
        base_url: "https://dev-api.upvest.com"
  
  stage:
    services:
      atomic:
        base_url: "https://staging-api.atomic.com"
      upvest:
        base_url: "https://staging-api.upvest.com"
  
  live:
    services:
      atomic:
        base_url: "https://api.atomic.com"
      upvest:
        base_url: "https://api.upvest.com" 