# Upvest Service Configuration
service:
  name: "upvest"
  base_url: "https://api.upvest.com"
  endpoints:
    "/accounts":
      method: "GET"
      uri: "/accounts"
    "/accounts/{id}":
      method: "GET"
      uri: "/accounts/{id}"
    "/accounts/{id}/transactions":
      method: "GET"
      uri: "/accounts/{id}/transactions" 