# Atomic Service Configuration
service:
  name: "atomic"
  base_url: "https://api.chucknorris.io"
  environments:
    dev: "https://api.chucknorris.io"
    stage: "https://api.chucknorris.io"
    live: "https://api.atomic.com"
  endpoints:
    GetAccount:
      method: "GET"
      uri: "/jokes/random"
    CreateAccount:
      method: "POST"
      uri: "/accounts"
    UpdateAccount:
      method: "PUT"
      uri: "/accounts/%s"
    DeleteAccount:
      method: "DELETE"
      uri: "/accounts/%s" 
