# Upvest Service Configuration
service:
  name: "upvest"
  base_url: "http://upvest-service.fleet.dev.eu-west-1.sumup.net"
  environments:
    dev: "http://upvest-service.fleet.dev.eu-west-1.sumup.net"
    stage: "http://upvest-service.fleet.dev.eu-west-1.sumup.net"
    live: "http://upvest-service.fleet.dev.eu-west-1.sumup.net"
  endpoints:
    GetAccount:
      method: "GET"
      uri: "/accounts"
    CreateAccount:
      method: "POST"
      uri: "/accounts"
    UpdateAccount:
      method: "PUT"
      uri: "/accounts/%s"
    DeleteAccount:
      method: "DELETE"
      uri: "/accounts/%s" 